name: Update blog posts
on:
  schedule:
    - cron: '0 17 * * 0'  # Sunday at 5:00 PM UTC (Monday midnight Jakarta time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Record start time
        id: start
        run: echo "time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Fetch feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@obiwancenobi"
          
      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            END_TIME=$(date +%s)
            START_TIME=${{ steps.start.outputs.time }}
            DURATION=$((END_TIME - START_TIME))
            MINUTES=$((DURATION / 60))
            SECONDS=$((DURATION % 60))
            
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add README.md
            git commit -m "Update blog posts"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push
            curl -H "Content-Type: application/json" \
               -d "{
                 \"embeds\": [{
                   \"title\": \"✅ Update README.md with new posts succeeded\",
                   \"color\": 3066993,
                   \"thumbnail\": { \"url\": \"https://github.com/${{ github.actor }}.png\" },
                   \"fields\": [
                     { \"name\": \"Repository\", \"value\": \"${{ github.repository }}\", \"inline\": true },
                     { \"name\": \"Branch\", \"value\": \"${{ github.ref_name }}\", \"inline\": true },
                     { \"name\": \"Commit\", \"value\": \"\`${{ github.sha }}\`\n${{ github.event.head_commit.message }}\" },
                     { \"name\": \"Author\", \"value\": \"${{ github.actor }}\", \"inline\": true },
                     { \"name\": \"Run\", \"value\": \"[View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\" },
                     { \"name\": \"Duration\", \"value\": \"${MINUTES}m ${SECONDS}s\", \"inline\": true }
                   ]
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK }}
          else
            END_TIME=$(date +%s)
            START_TIME=${{ steps.start.outputs.time }}
            DURATION=$((END_TIME - START_TIME))
            MINUTES=$((DURATION / 60))
            SECONDS=$((DURATION % 60))
            echo "No changes to commit"
            curl -H "Content-Type: application/json" \
               -d "{
                 \"embeds\": [{
                   \"title\": \"✅ No new post\",
                   \"color\": 3066993,
                   \"thumbnail\": { \"url\": \"https://github.com/${{ github.actor }}.png\" },
                   \"fields\": [
                     { \"name\": \"Repository\", \"value\": \"${{ github.repository }}\", \"inline\": true },
                     { \"name\": \"Branch\", \"value\": \"${{ github.ref_name }}\", \"inline\": true },
                     { \"name\": \"Commit\", \"value\": \"\`${{ github.sha }}\`\n${{ github.event.head_commit.message }}\" },
                     { \"name\": \"Author\", \"value\": \"${{ github.actor }}\", \"inline\": true },
                     { \"name\": \"Run\", \"value\": \"[View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\" },
                     { \"name\": \"Duration\", \"value\": \"${MINUTES}m ${SECONDS}s\", \"inline\": true }
                   ]
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
